Collectie van een aantal encodings:
Deze puzzel maakt een reis door acht locaties, soms groot, soms klein. Welke acht locaties?
```
CBDIFBIANCDIOBBEAO
YVKMFCXVEUVTFFIUZERRKZJUWVXFUVUETTTTWSTFUVJJCVLKVCZJUVCFTRKZV
EOKVITARRREIWSVOOKSKEMXBEWWOEJWCILNIGQYLRXREENEGPAMMIE
NTFUESAAMILGGOATAEHEKESDNEEHTRFINEIEECWGG
XRNAKAGNIDVPXGKMTFZOYIONYCM
CBECCCVEQCEOBPQUDAEPCVKKITSVCHCVWXKKCVEPDIPQIDNCHCBYUPHECY
PHNQIDMRUKBVIHCXRASVQVOKHY
```

Regel 2 lijkt een ceasar codering van 17 te gebruiken:
`HETVOLGENDECOORDINAATISDFEGODEDNCCCCFBCODESSLEUTELISDELOCATIE` Ofwel, het volgende coordinaat is `DFEGODEDNCCCCFBCODES` sleutel is de locatie.
